version: "3"
services:

  www:
    image: shyamendrahazra/php-apache
    volumes:
      - "./app:/var/www/html"
    ports:
      - 80:80
    environment:
      - DATABASE
      - USERNAME
  db:
    image: mysql
    volumes:
        - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306