version: "3"
services:

  www:    
    build: .
    volumes:
      - "./app:/var/www/html"
    container_name:
      php-app
    ports:
      - 80:80
    environment:
      - HOSTNAME
      - USERNAME
      - PASSWORD
      - DATABASE


  mysql:
    image: mysql
    container_name: MySQL
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      - DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=1


  phpmyadmin:
    image: phpmyadmin
    container_name: PHPMYADMIN
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306