version: "3.8"
services:

  php_apache:    
    build: .
    volumes:
      - "./app:/var/www/html"
    container_name: php-app
    ports:
      - 80:80
    environment:
      - HOSTNAME
      - USERNAME
      - PASSWORD
      - DATABASE

  mysql:
    build: 
      context: ./mysql.conf/
    container_name: MySQL
    environment:
      - MYSQL_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=Asia/Kolkata
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
